overwrite: true
schema: 'https://useheadless.wpengine.com/graphql'
documents: 'src/lib/graphql/**/*.graphql'
generates:
  src/lib/graphql/_generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'urql-introspection'
      - 'typescript-urql'
    config:
      withRefetchFn: true
      documentVariableSuffix: 'Query'
      namingConvention:
        typeNames: change-case-all#pascalCase
        enumValues: change-case-all#upperCase
